import './styles.css';
import * as BABYLON from 'https://cdn.jsdelivr.net/npm/babylonjs@8.33.1/+esm';

const W=24,H=24,TYPES=['residential','commercial','industrial','park','road','bus','train'];
const DEF={sandbox:{cash:250000,speed:6},challenge:{cash:90000,speed:8},hard:{cash:45000,speed:10}};
const B={residential:{cost:550,cap:55,jobs:2,tax:7,color:'#4fa3ff',unlock:0},commercial:{cost:850,cap:0,jobs:38,tax:18,color:'#ffd166',unlock:75},industrial:{cost:1050,cap:0,jobs:70,tax:23,color:'#b08968',unlock:180},park:{cost:400,cap:0,jobs:0,tax:0,color:'#7bd36b',unlock:0},road:{cost:80,cap:0,jobs:0,tax:0,color:'#555',unlock:0},bus:{cost:2200,cap:0,jobs:10,tax:-6,color:'#7c3aed',unlock:300},train:{cost:6500,cap:0,jobs:35,tax:-18,color:'#06b6d4',unlock:900}};
class Store{static save(g){localStorage.cityBuilderSave=JSON.stringify(g.serialize())}static load(){try{return JSON.parse(localStorage.cityBuilderSave)}catch{return null}}}
class Sim{
 constructor(diff='challenge',data){this.diff=diff;this.cash=DEF[diff].cash;this.day=1;this.hour=7;this.season=0;this.weather='clear';this.pop=0;this.happy=72;this.speed=DEF[diff].speed;this.notifications=[];this.goals=[['Reach 500 population',s=>s.pop>=500,8000,false],['Build 10 commercial zones',s=>s.count('commercial')>=10,7000,false],['Reduce congestion below 35%',s=>s.congestion<35&&s.pop>250,6500,false],['Reach 85 happiness',s=>s.happy>=85,6000,false]];this.nextDecision=14;this.traffic=[];this.grid=[];for(let z=0;z<H;z++)for(let x=0;x<W;x++)this.grid.push({x,z,e:Math.max(0,Math.round((Math.sin(x*.45)+Math.cos(z*.38))*1.1+Math.random()*1.7)),type:null,b:null}); if(data){let savedGoals=data.goals;Object.assign(this,data);this.goals=this.goals.map((g,i)=>[g[0],g[1],g[2],savedGoals?.[i]?.[3]||false]);}}
 tile(x,z){return this.grid.find(t=>t.x===x&&t.z===z)} count(t){return this.grid.filter(c=>c.type===t).length} unlocked(t){return this.pop>=B[t].unlock} place(x,z,type){let c=this.tile(x,z),d=B[type]; if(!c||!d||!this.unlocked(type)||this.cash<d.cost)return false; if(type!=='road'&&type!=='bus'&&type!=='train'&&c.type==='road')return false; c.type=type;c.b={lvl:1,age:0};this.cash-=d.cost;this.note(`${type} placed`);return true}
 stats(){let cap=0,jobs=0,tax=0,exp=0;for(const c of this.grid)if(c.type){let d=B[c.type];cap+=d.cap*(c.b?.lvl||1);jobs+=d.jobs*(c.b?.lvl||1);tax+=d.tax;exp+=c.type==='road'?2:c.type==='bus'?35:c.type==='train'?90:0}return{cap,jobs,tax,exp}}
 roadNeighbors(n){return [[1,0],[-1,0],[0,1],[0,-1]].map(([a,b])=>this.tile(n.x+a,n.z+b)).filter(t=>t&&['road','bus','train'].includes(t.type))}
 path(a,b){let open=[a],came=new Map(),g=new Map([[a,0]]),key=t=>t.x+','+t.z;while(open.length){open.sort((u,v)=>(g.get(u)+Math.abs(u.x-b.x)+Math.abs(u.z-b.z))-(g.get(v)+Math.abs(v.x-b.x)+Math.abs(v.z-b.z)));let cur=open.shift();if(cur===b){let p=[cur];while(came.has(key(cur))){cur=came.get(key(cur));p.unshift(cur)}return p}for(const nb of this.roadNeighbors(cur)){let ng=g.get(cur)+1;if(ng<(g.get(nb)??1e9)){came.set(key(nb),cur);g.set(nb,ng);if(!open.includes(nb))open.push(nb)}}}return[]}
 nearestRoad(c){return this.grid.filter(t=>['road','bus','train'].includes(t.type)).sort((a,b)=>Math.abs(a.x-c.x)+Math.abs(a.z-c.z)-Math.abs(b.x-c.x)-Math.abs(b.z-c.z))[0]}
 spawnTraffic(){let homes=this.grid.filter(c=>c.type==='residential'),works=this.grid.filter(c=>['commercial','industrial'].includes(c.type));if(!homes.length||!works.length)return;let h=homes[Math.random()*homes.length|0],w=works[Math.random()*works.length|0],a=this.nearestRoad(h),b=this.nearestRoad(w);if(a&&b){let p=this.path(a,b);if(p.length>1)this.traffic.push({p,i:0,kind:this.grid.some(t=>t.type==='bus'||t.type==='train')&&Math.random()<.35?'transit':'car'})}}
 tick(dt){let inc=dt*this.speed/60;this.hour+=inc*24;if(this.hour>=24){this.hour-=24;this.day++;if(this.day%30===0)this.season=(this.season+1)%4;if(this.day%7===0)this.weather=['clear','rain','fog','snow'][Math.random()*4|0]}let st=this.stats(),demand=Math.min(st.cap,st.jobs*1.25),growth=Math.max(0,demand-this.pop)*.006*dt*this.speed;this.pop+=growth;let transit=this.count('bus')*4+this.count('train')*10;this.congestion=Math.max(0,Math.min(100,this.traffic.length*1.7-transit));this.happy=Math.max(0,Math.min(100,70+this.count('park')*2+transit*.4-this.congestion*.35+(this.weather==='clear'?3:-2)));this.cash+=(st.tax*this.pop/1000-st.exp)*dt*this.speed; if(Math.random()<.035*dt*this.speed)this.spawnTraffic();this.traffic=this.traffic.filter(v=>(v.i+=dt*(v.kind==='transit'?1.3:2.2))<v.p.length-1);for(const g of this.goals)if(!g[3]&&g[1](this)){g[3]=true;this.cash+=g[2];this.note(`Goal complete: ${g[0]} +$${g[2]}`)}if(this.day>=this.nextDecision){this.nextDecision+=14;this.decision={title:'Mayor Decision',opts:[['Green grants',-4000,8],['Business tax break',6000,-4],['Traffic campaign',-2500,5]]}}}
 choose(i){let o=this.decision.opts[i];this.cash+=o[1];this.happy+=o[2];this.note(`Policy enacted: ${o[0]}`);this.decision=null} note(t){this.notifications.unshift({t,at:Date.now()});this.notifications=this.notifications.slice(0,6)} serialize(){return{diff:this.diff,cash:this.cash,day:this.day,hour:this.hour,season:this.season,weather:this.weather,pop:this.pop,happy:this.happy,speed:this.speed,goals:this.goals.map(g=>[g[0],null,g[2],g[3]]),grid:this.grid,nextDecision:this.nextDecision}}
}
class View{constructor(sim){this.sim=sim;this.sel='road';this.quality='high';this.canvas=document.createElement('canvas');this.canvas.id='renderCanvas';document.body.append(this.canvas);this.engine=new BABYLON.Engine(this.canvas,true,{preserveDrawingBuffer:true,stencil:true});this.scene=new BABYLON.Scene(this.engine);this.camera=new BABYLON.ArcRotateCamera('cam',-Math.PI/4,1.05,42,new BABYLON.Vector3(W/2,0,H/2),this.scene);this.camera.attachControl(this.canvas,true);this.camera.lowerRadiusLimit=12;this.camera.upperRadiusLimit=85;this.sun=new BABYLON.DirectionalLight('sun',new BABYLON.Vector3(-.6,-1,-.4),this.scene);this.sun.position=new BABYLON.Vector3(20,40,20);this.shadow=new BABYLON.ShadowGenerator(1024,this.sun);this.shadow.useBlurExponentialShadowMap=true;new BABYLON.HemisphericLight('hemi',new BABYLON.Vector3(0,1,0),this.scene).intensity=.35;this.mats={};for(const [k,v] of Object.entries(B))this.mats[k]=this.mat(v.color);this.mats.ground=this.mat('#3f7d44');this.mats.water=this.mat('#245a88');this.root=new BABYLON.TransformNode('city',this.scene);this.meshes=new Map();this.vehicles=[];this.sky=BABYLON.MeshBuilder.CreateBox('sky',{size:900},this.scene);this.sky.material=this.mat('#7dc8ff');this.sky.material.backFaceCulling=false;this.buildTerrain();this.ui();this.scene.onPointerObservable.add(e=>{if(e.type===BABYLON.PointerEventTypes.POINTERPICK&&e.pickInfo.hit){let m=e.pickInfo.pickedMesh;if(m.metadata?.cell)this.place(m.metadata.cell)}});this.engine.runRenderLoop(()=>this.loop());addEventListener('resize',()=>this.engine.resize())}
 mat(c){let m=new BABYLON.StandardMaterial(c,this.scene);m.diffuseColor=BABYLON.Color3.FromHexString(c);m.specularColor=new BABYLON.Color3(.08,.08,.08);return m}
 buildTerrain(){this.sim.grid.forEach(c=>{let box=BABYLON.MeshBuilder.CreateBox('t',{width:.96,depth:.96,height:.18+c.e*.18},this.scene);box.position.set(c.x,box.scaling.y/2+c.e*.09,c.z);box.material=this.mats.ground;box.metadata={cell:c};box.receiveShadows=true;this.meshes.set(c,box)})}
 place(c){if(this.sim.place(c.x,c.z,this.sel))this.refreshCell(c)} refreshCell(c){if(c.mesh)c.mesh.dispose();if(!c.type)return;let h=c.type==='road'?0.04:c.type==='park'?.18:c.type==='bus'?.35:c.type==='train'?.28:.8+(c.b.lvl*.22)+Math.random()*.8;let m=BABYLON.MeshBuilder.CreateBox('b',{width:.72,depth:.72,height:h},this.scene);m.position.set(c.x,c.e*.18+.18+h/2,c.z);m.material=this.mats[c.type];m.metadata={cell:c};this.shadow.addShadowCaster(m);c.mesh=m}
 sync(){this.sim.grid.forEach(c=>{if(c.type&&!c.mesh)this.refreshCell(c)})}
 loop(){let dt=this.engine.getDeltaTime()/1000;this.sim.tick(dt);let dayFrac=this.sim.hour/24,int=.25+Math.max(0,Math.sin(dayFrac*Math.PI))*1.1;this.sun.intensity=int;this.scene.fogMode=this.sim.weather==='fog'?BABYLON.Scene.FOGMODE_EXP2:BABYLON.Scene.FOGMODE_NONE;this.scene.clearColor=BABYLON.Color4.FromHexString(this.sim.weather==='snow'?'#c9d8e8ff':this.sim.weather==='rain'?'#68788cff':'#87ceebff');this.drawVehicles();this.updateUI();this.scene.render()}
 drawVehicles(){for(const v of this.vehicles)v.dispose();this.vehicles=[];for(const t of this.sim.traffic){let a=t.p[Math.floor(t.i)],b=t.p[Math.ceil(t.i)]||a,l=t.i%1,x=a.x+(b.x-a.x)*l,z=a.z+(b.z-a.z)*l;let s=t.kind==='transit'?0.25:.16,m=BABYLON.MeshBuilder.CreateBox('v',{width:s,depth:s*1.6,height:s},this.scene);m.position.set(x,.55,z);m.material=this.mat(t.kind==='transit'?'#a855f7':'#ef4444');this.vehicles.push(m)}}
 ui(){document.body.insertAdjacentHTML('beforeend',`<div id="start"><h1>Civic Skyline 3D</h1><p>Build, zone, govern, and simulate a living isometric city.</p><select id="diff"><option>challenge</option><option>sandbox</option><option>hard</option></select><button id="new">New City</button><button id="load">Load City</button></div><div id="hud"><div id="stats"></div><div id="tools"></div><div id="goals"></div><div id="notes"></div></div><div id="panels"><button id="save">Save</button><button id="opt">Options</button><button id="dev">Dev</button></div><div id="modal"></div>`);TYPES.forEach(t=>tools.innerHTML+=`<button data-t="${t}">${t}</button>`);tools.onclick=e=>{if(e.target.dataset.t)this.sel=e.target.dataset.t};new.onclick=()=>{start.style.display='none'};load.onclick=()=>{let d=Store.load();if(d){this.sim=new Sim(d.diff,d);this.sync();start.style.display='none'}};save.onclick=()=>{Store.save(this.sim);this.sim.note('City saved')};opt.onclick=()=>modal.innerHTML=`<section><h2>Options</h2><label>Graphics <select onchange="view.quality=this.value"><option>high</option><option>medium</option><option>low</option></select></label><label>Game speed <input type=range min=1 max=20 value=${this.sim.speed} oninput="view.sim.speed=this.value"></label><button onclick="modal.innerHTML=''">Close</button></section>`;dev.onclick=()=>modal.innerHTML=`<section><h2>Developer</h2><button onclick="view.sim.cash+=50000">+$50k</button><button onclick="view.sim.pop+=500">+Pop</button><pre id=dump></pre><button onclick="modal.innerHTML=''">Close</button></section>`;window.view=this}
 updateUI(){stats.innerHTML=`$${this.sim.cash.toFixed(0)} · Pop ${this.sim.pop|0} · Happy ${this.sim.happy|0}% · Congestion ${this.sim.congestion|0}% · Day ${this.sim.day} ${this.sim.hour|0}:00 · ${['Spring','Summer','Autumn','Winter'][this.sim.season]} · ${this.sim.weather}`;goals.innerHTML=this.sim.goals.map(g=>`<div class=${g[3]?'done':''}>${g[0]} ${g[3]?'✓':''}</div>`).join('');notes.innerHTML=this.sim.notifications.map(n=>`<div>${n.t}</div>`).join('');if(this.sim.decision)modal.innerHTML=`<section><h2>${this.sim.decision.title}</h2>${this.sim.decision.opts.map((o,i)=>`<button onclick="view.sim.choose(${i});modal.innerHTML=''">${o[0]} (${o[1]>0?'+':''}$${o[1]}, ${o[2]>0?'+':''}${o[2]} happy)</button>`).join('')}</section>`;let d=document.getElementById('dump');if(d)d.textContent=JSON.stringify({traffic:this.sim.traffic.length,cash:this.sim.cash,pop:this.sim.pop},null,2)} }
new View(new Sim());
